alias rm='rm -fr'
alias ls='exa --long --all --no-user --group-directories-first --git --sort=ext --sort=size --header'
alias ll='exa --long --all --no-user --group-directories-first --git --sort=ext --sort=size --header'
alias l='exa --long --all --no-user --group-directories-first --git --sort=ext --sort=size --header'
alias g='git'
alias open='xdg-open'
alias code='code .'
alias dnfu='sudo dnf up'
alias xx='exit'
alias oo='sudo reboot'
alias qq='sudo poweroff'
