# Set the control character to Ctrl+Spacebar (instead of Ctrl+B)
set -g prefix C-space
unbind-key C-b
bind-key C-space send-prefix

##########################################################
# Tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
##########################################################

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Enable mouse mode
set -g mouse on

# tmux-yank config
set -g @yank_selection_mouse 'clipboard'
set -s copy-command 'wl-copy'
set -g set-clipboard on
set -g @yank_selection 'primary'
set -g @yank_action 'copy-pipe-no-clear'

# Move status bar to the top
set -g status-position top

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Re-number windows
set -g renumber-windows on

# Init TPM
run '~/.config/tmux/plugins/tpm/tpm'
